### ISSUE TITLE
Password must have at least 8 characters

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/project2#20]
Password must have at least 8 characters, yet, while we put 1-7 digits, an alert pops-up with a BAD REQUEST error, but sharing no reason why.

![image](https://github.com/1alyciaoliveira/project2/assets/108914238/ea1a6efd-1d26-4927-93fa-f64b3eb50901)

**Comment by 1alyciaoliveira** [comment]
Same thing is happening if you type your password wrongly when logging.

**Comment by JessFarron** [comment]
Sign up errors covered

**Comment by JessFarron** [comment]
Alerts displaying the error reasoncorrectly
