### ISSUE TITLE
Logout should be done automatically only after inactivity time

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/project2#22]
Currently, the logout is being done after 5 min of login, no matter if the person is active or not.
Activity time should be taken into consideration.

**Comment by santis1001** [comment]
req.session.touch();
Every time the auth middleware is use it extend the time of the session
The expiration time is extended to the next 300000ms

| wz2a5ItZB6uIKHC4Z2kiOiU6U_Bp92Uv | **2023-06-24 17:29:23** | {"cookie":{"originalMaxAge":300000,"expires":"2023-06-24T17:26:30.470Z","secure":false,"httpOnly":true,"path":"/","sameSite":"strict"},"user_id":1,"logged_in":true} | 2023-06-24 17:20:59 | 2023-06-24 17:24:23 |

| wz2a5ItZB6uIKHC4Z2kiOiU6U_Bp92Uv | **2023-06-24 17:30:05** | {"cookie":{"originalMaxAge":300000,"expires":"2023-06-24T17:26:30.470Z","secure":false,"httpOnly":true,"path":"/","sameSite":"strict"},"user_id":1,"logged_in":true} | 2023-06-24 17:20:59 | 2023-06-24 17:25:05 |
