### ISSUE TITLE
Description + target date - are we using it?

### ISSUE THREAD

**Issue by 1alyciaoliveira** [1alyciaoliveira/project2#26]
When adding a new goal, the user is requested to fill a target date + a description of the goal. But this information is not being used anywhere. Start to use it or remove it?

![image](https://github.com/1alyciaoliveira/project2/assets/108914238/d5fe594c-13ab-47c3-90f6-620ee4701c73)

**Comment by santis1001** [comment]
The description is being actively used, while target date isn't.

**Comment by 1alyciaoliveira** [comment]
Description was added to the card, target date was removed.
